### ISSUE TITLE
have aarch64 whl files

### ISSUE THREAD

**Issue by galak** [pyocd/cmsis-pack-manager#151]
To make life easier would be nice if there was linux aarch64 whl on release.

**Comment by theotherjimmy** [comment]
Has a standard come out for aarch64 wheels? I don't recall their being one when I last checked, 2 years ago.

**Comment by flit** [comment]
AArch64 is supported now by `manylinux2014` defined by [PEP 599](https://www.python.org/dev/peps/pep-0599/).

See this blog:
https://marcin.juszkiewicz.com.pl/2019/12/04/python-and-aarch64/

**Comment by galak** [comment]
Any updates on this?

**Comment by mathias-arm** [comment]
We will try to add this when we make the next release.

**Comment by pfalcon** [comment]
Note that cmsis-pack-manager is (again) the hard dependency of pyocd, in particular instructions describing how to get around need to install cmsis-pack-manager to use pyocd: https://github.com/pyocd/pyOCD/blob/master/docs/installing_on_non_x86.md - no longer work with the latest pyocd (0.29) and/or recent Python: https://github.com/pyocd/pyOCD/issues/1023 .

@galak, FYI

**Comment by flit** [comment]
@galak cmsis-pack-manager 0.3.0 is released with AArch64 wheels. GitHub Actions workflows are set up so all future releases will support AArch64.
