### ISSUE TITLE
Is milksnake a runtime dependency?

### ISSUE THREAD

**Issue by dvzrv** [pyocd/cmsis-pack-manager#188]
The [setup.cfg](https://github.com/pyocd/cmsis-pack-manager/blob/5b61d18925c1bbdc3a98c658b99c00b01690a44f/setup.cfg#L39) denotes milksnake as a runtime dependency, but I believe that is very likely an error (it's used during setup, but not during runtime).

It would be great to get confirmation on this, then I can open a PR to remove it :)

**Comment by mbrossard** [comment]
Could you try to build the [maturin](https://github.com/pyocd/cmsis-pack-manager/tree/maturin) branch? I am not sure I have properly connected all the pieces. I need to update GitHub Actions configuration, and `setuptools_scm` needs to be replaced.

**Comment by dvzrv** [comment]
milksnake is unfortunately still present in setup.cfg and will unconditionally drag it in upon installing this project.
